-- 部・編・幕の番号が頭に付くラベル（「24億脱出編4」「第2部[9]」）は旧 volSort で先頭の数字（24, 2）に
-- なり、全巻が同じ値で並び順が崩れていた（C420374 等）。今の volSort（部の番号 ×1000 + 巻番号）で付け直す。
-- scripts/ingest.mjs で取り込み直した DB には不要（同じ値になる）。
UPDATE volumes SET vol_sort = 2015012 WHERE vol_sort = 2015 AND volume_number = '2015年12';
UPDATE volumes SET vol_sort = 24001 WHERE vol_sort = 24 AND volume_number = '24億脱出編1';
UPDATE volumes SET vol_sort = 24010 WHERE vol_sort = 24 AND volume_number = '24億脱出編10';
UPDATE volumes SET vol_sort = 24011 WHERE vol_sort = 24 AND volume_number = '24億脱出編11';
UPDATE volumes SET vol_sort = 24012 WHERE vol_sort = 24 AND volume_number = '24億脱出編12';
UPDATE volumes SET vol_sort = 24013 WHERE vol_sort = 24 AND volume_number = '24億脱出編13';
UPDATE volumes SET vol_sort = 24014 WHERE vol_sort = 24 AND volume_number = '24億脱出編14';
UPDATE volumes SET vol_sort = 24015 WHERE vol_sort = 24 AND volume_number = '24億脱出編15';
UPDATE volumes SET vol_sort = 24016 WHERE vol_sort = 24 AND volume_number = '24億脱出編16';
UPDATE volumes SET vol_sort = 24017 WHERE vol_sort = 24 AND volume_number = '24億脱出編17';
UPDATE volumes SET vol_sort = 24018 WHERE vol_sort = 24 AND volume_number = '24億脱出編18';
UPDATE volumes SET vol_sort = 24019 WHERE vol_sort = 24 AND volume_number = '24億脱出編19';
UPDATE volumes SET vol_sort = 24002 WHERE vol_sort = 24 AND volume_number = '24億脱出編2';
UPDATE volumes SET vol_sort = 24020 WHERE vol_sort = 24 AND volume_number = '24億脱出編20';
UPDATE volumes SET vol_sort = 24021 WHERE vol_sort = 24 AND volume_number = '24億脱出編21';
UPDATE volumes SET vol_sort = 24022 WHERE vol_sort = 24 AND volume_number = '24億脱出編22';
UPDATE volumes SET vol_sort = 24023 WHERE vol_sort = 24 AND volume_number = '24億脱出編23';
UPDATE volumes SET vol_sort = 24024 WHERE vol_sort = 24 AND volume_number = '24億脱出編24';
UPDATE volumes SET vol_sort = 24025 WHERE vol_sort = 24 AND volume_number = '24億脱出編25';
UPDATE volumes SET vol_sort = 24026 WHERE vol_sort = 24 AND volume_number = '24億脱出編26';
UPDATE volumes SET vol_sort = 24003 WHERE vol_sort = 24 AND volume_number = '24億脱出編3';
UPDATE volumes SET vol_sort = 24004 WHERE vol_sort = 24 AND volume_number = '24億脱出編4';
UPDATE volumes SET vol_sort = 24005 WHERE vol_sort = 24 AND volume_number = '24億脱出編5';
UPDATE volumes SET vol_sort = 24006 WHERE vol_sort = 24 AND volume_number = '24億脱出編6';
UPDATE volumes SET vol_sort = 24007 WHERE vol_sort = 24 AND volume_number = '24億脱出編7';
UPDATE volumes SET vol_sort = 24008 WHERE vol_sort = 24 AND volume_number = '24億脱出編8';
UPDATE volumes SET vol_sort = 24009 WHERE vol_sort = 24 AND volume_number = '24億脱出編9';
UPDATE volumes SET vol_sort = 1001 WHERE vol_sort = 1 AND volume_number = '第1幕 1';
UPDATE volumes SET vol_sort = 1002 WHERE vol_sort = 1 AND volume_number = '第1幕 2';
UPDATE volumes SET vol_sort = 1003 WHERE vol_sort = 1 AND volume_number = '第1幕 3';
UPDATE volumes SET vol_sort = 1004 WHERE vol_sort = 1 AND volume_number = '第1幕 4';
UPDATE volumes SET vol_sort = 1005 WHERE vol_sort = 1 AND volume_number = '第1幕 5';
UPDATE volumes SET vol_sort = 1006 WHERE vol_sort = 1 AND volume_number = '第1幕 6';
UPDATE volumes SET vol_sort = 1007 WHERE vol_sort = 1 AND volume_number = '第1幕 7';
UPDATE volumes SET vol_sort = 1001 WHERE vol_sort = 1 AND volume_number = '第1部 1';
UPDATE volumes SET vol_sort = 1007 WHERE vol_sort = 1 AND volume_number = '第1部[7]';
UPDATE volumes SET vol_sort = 2001 WHERE vol_sort = 2 AND volume_number = '第2幕 1';
UPDATE volumes SET vol_sort = 2002 WHERE vol_sort = 2 AND volume_number = '第2幕 2';
UPDATE volumes SET vol_sort = 2003 WHERE vol_sort = 2 AND volume_number = '第2幕 3';
UPDATE volumes SET vol_sort = 2004 WHERE vol_sort = 2 AND volume_number = '第2幕 4';
UPDATE volumes SET vol_sort = 2005 WHERE vol_sort = 2 AND volume_number = '第2幕 5';
UPDATE volumes SET vol_sort = 2006 WHERE vol_sort = 2 AND volume_number = '第2幕 6';
UPDATE volumes SET vol_sort = 2007 WHERE vol_sort = 2 AND volume_number = '第2幕 7';
UPDATE volumes SET vol_sort = 2008 WHERE vol_sort = 2 AND volume_number = '第2幕 8';
UPDATE volumes SET vol_sort = 2009 WHERE vol_sort = 2 AND volume_number = '第2幕 9';
UPDATE volumes SET vol_sort = 2002 WHERE vol_sort = 2 AND volume_number = '第2部 2';
UPDATE volumes SET vol_sort = 2004 WHERE vol_sort = 2 AND volume_number = '第2部 4';
UPDATE volumes SET vol_sort = 2016 WHERE vol_sort = 2 AND volume_number = '第2部 round 16';
UPDATE volumes SET vol_sort = 2001 WHERE vol_sort = 2 AND volume_number = '第2部1';
UPDATE volumes SET vol_sort = 2002 WHERE vol_sort = 2 AND volume_number = '第2部2';
UPDATE volumes SET vol_sort = 2010 WHERE vol_sort = 2 AND volume_number = '第2部[10]';
UPDATE volumes SET vol_sort = 2011 WHERE vol_sort = 2 AND volume_number = '第2部[11]';
UPDATE volumes SET vol_sort = 2012 WHERE vol_sort = 2 AND volume_number = '第2部[12]';
UPDATE volumes SET vol_sort = 2013 WHERE vol_sort = 2 AND volume_number = '第2部[13]';
UPDATE volumes SET vol_sort = 2001 WHERE vol_sort = 2 AND volume_number = '第2部[1]';
UPDATE volumes SET vol_sort = 2002 WHERE vol_sort = 2 AND volume_number = '第2部[2]';
UPDATE volumes SET vol_sort = 2003 WHERE vol_sort = 2 AND volume_number = '第2部[3]';
UPDATE volumes SET vol_sort = 2004 WHERE vol_sort = 2 AND volume_number = '第2部[4]';
UPDATE volumes SET vol_sort = 2005 WHERE vol_sort = 2 AND volume_number = '第2部[5]';
UPDATE volumes SET vol_sort = 2006 WHERE vol_sort = 2 AND volume_number = '第2部[6]';
UPDATE volumes SET vol_sort = 2007 WHERE vol_sort = 2 AND volume_number = '第2部[7]';
UPDATE volumes SET vol_sort = 2008 WHERE vol_sort = 2 AND volume_number = '第2部[8]';
UPDATE volumes SET vol_sort = 2009 WHERE vol_sort = 2 AND volume_number = '第2部[9]';
UPDATE volumes SET vol_sort = 3001 WHERE vol_sort = 3 AND volume_number = '第3幕 1';
UPDATE volumes SET vol_sort = 3002 WHERE vol_sort = 3 AND volume_number = '第3幕 2';
UPDATE volumes SET vol_sort = 3003 WHERE vol_sort = 3 AND volume_number = '第3幕 3';
UPDATE volumes SET vol_sort = 3004 WHERE vol_sort = 3 AND volume_number = '第3幕 4';
UPDATE volumes SET vol_sort = 3005 WHERE vol_sort = 3 AND volume_number = '第3幕 5';
UPDATE volumes SET vol_sort = 3006 WHERE vol_sort = 3 AND volume_number = '第3幕 6';
UPDATE volumes SET vol_sort = 3025 WHERE vol_sort = 3 AND volume_number = '第3部 round 25';
UPDATE volumes SET vol_sort = 3010 WHERE vol_sort = 3 AND volume_number = '第3部[10]';
UPDATE volumes SET vol_sort = 3001 WHERE vol_sort = 3 AND volume_number = '第3部[1]';
UPDATE volumes SET vol_sort = 3002 WHERE vol_sort = 3 AND volume_number = '第3部[2]';
UPDATE volumes SET vol_sort = 3003 WHERE vol_sort = 3 AND volume_number = '第3部[3]';
UPDATE volumes SET vol_sort = 3004 WHERE vol_sort = 3 AND volume_number = '第3部[4]';
UPDATE volumes SET vol_sort = 3005 WHERE vol_sort = 3 AND volume_number = '第3部[5]';
UPDATE volumes SET vol_sort = 3006 WHERE vol_sort = 3 AND volume_number = '第3部[6]';
UPDATE volumes SET vol_sort = 3007 WHERE vol_sort = 3 AND volume_number = '第3部[7]';
UPDATE volumes SET vol_sort = 3008 WHERE vol_sort = 3 AND volume_number = '第3部[8]';
UPDATE volumes SET vol_sort = 3009 WHERE vol_sort = 3 AND volume_number = '第3部[9]';
UPDATE volumes SET vol_sort = 4010 WHERE vol_sort = 4 AND volume_number = '第4部[10]';
UPDATE volumes SET vol_sort = 4011 WHERE vol_sort = 4 AND volume_number = '第4部[11]';
UPDATE volumes SET vol_sort = 4012 WHERE vol_sort = 4 AND volume_number = '第4部[12]';
UPDATE volumes SET vol_sort = 4001 WHERE vol_sort = 4 AND volume_number = '第4部[1]';
UPDATE volumes SET vol_sort = 4002 WHERE vol_sort = 4 AND volume_number = '第4部[2]';
UPDATE volumes SET vol_sort = 4003 WHERE vol_sort = 4 AND volume_number = '第4部[3]';
UPDATE volumes SET vol_sort = 4004 WHERE vol_sort = 4 AND volume_number = '第4部[4]';
UPDATE volumes SET vol_sort = 4005 WHERE vol_sort = 4 AND volume_number = '第4部[5]';
UPDATE volumes SET vol_sort = 4006 WHERE vol_sort = 4 AND volume_number = '第4部[6]';
UPDATE volumes SET vol_sort = 4007 WHERE vol_sort = 4 AND volume_number = '第4部[7]';
UPDATE volumes SET vol_sort = 4008 WHERE vol_sort = 4 AND volume_number = '第4部[8]';
UPDATE volumes SET vol_sort = 5001 WHERE vol_sort = 5 AND volume_number = '第5部[1]';
